name: Build and test
on: [push, pull_request]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system:
          - ubuntu-latest
        ocaml-version:
          - 4.07.x
          - 4.08.x
          - 4.09.x
          - 4.10.x
          - 4.11.x
    steps:
      - uses: actions/checkout@v3
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}
      - name: Install dependencies
        run: opam install . --deps-only --with-test
      - name: Build
        run: opam exec -- dune build @install @examples
      - name: Test
        run: opam exec -- dune runtest
